### ISSUE TITLE
team workspace

### ISSUE THREAD

**Issue by Jack-mi** [green-dalii/diflowy#8]
Could we support team space? Similar to dify team account, team members are able to edit some workflows together, and everyone can maintain different workflow versions simultaneously.

**Comment by green-dalii** [comment]
Great suggestion, we will consider adding this feature for premium users in the future, it may take a while due to the fact that it's only being developed for me at the moment!

**Comment by green-dalii** [comment]
We are working on the workspace feature in the dev branch, and will push it to the main branch when it is complete and fully tested. If you want to apply for the beta test, please contact Email: diflowy@greenerai.top

**Comment by green-dalii** [comment]
The workspace feature is currently supported, and we are in the process of beta testing the feature, so feel free to apply for beta testing for specific reference: #10 and [Our Blog](https://diflowy.greenerai.top/blog/diflowy-workspace-multi-user-collaboration-beta-launch-en/)

**Comment by green-dalii** [comment]
The workspace feature is currently supported, and we are in the process of beta testing the feature, so feel free to apply for beta testing for specific reference: #10 and [Our Blog](https://diflowy.greenerai.top/blog/diflowy-workspace-multi-user-collaboration-beta-launch-en/)
